// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetConfig():Promise<app.AppConfig>;

export function GetProjectIndex(arg1:app.IndexRequest):Promise<app.ProjectIndexResponse>;

export function GetReport(arg1:app.ReportRequest):Promise<app.ReportResponse>;

export function GetRunner():Promise<app.RunnerInfo>;

export function GetSessionConversation(arg1:app.SessionPreviewRequest):Promise<app.SessionConversationResponse>;

export function GetSessionPreview(arg1:app.SessionPreviewRequest):Promise<app.SessionPreviewResponse>;

export function OpenPathInFinder(arg1:string):Promise<void>;

export function OpenProjectInFinder(arg1:string):Promise<void>;

export function RefreshProjectIndex(arg1:app.IndexRequest):Promise<app.ProjectIndexResponse>;

export function SaveConfig(arg1:app.AppConfig):Promise<app.AppConfig>;
