// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetProjectIndex() {
  return window['go']['main']['App']['GetProjectIndex']();
}

export function GetReport(arg1) {
  return window['go']['main']['App']['GetReport'](arg1);
}

export function GetRunner() {
  return window['go']['main']['App']['GetRunner']();
}

export function GetSessionConversation(arg1) {
  return window['go']['main']['App']['GetSessionConversation'](arg1);
}

export function GetSessionPreview(arg1) {
  return window['go']['main']['App']['GetSessionPreview'](arg1);
}

export function OpenPathInFinder(arg1) {
  return window['go']['main']['App']['OpenPathInFinder'](arg1);
}

export function OpenProjectInFinder(arg1) {
  return window['go']['main']['App']['OpenProjectInFinder'](arg1);
}

export function RefreshProjectIndex(arg1) {
  return window['go']['main']['App']['RefreshProjectIndex'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
