// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.AppConfig>;

export function GetProjectIndex():Promise<main.ProjectIndexResponse>;

export function GetReport(arg1:main.ReportRequest):Promise<main.ReportResponse>;

export function GetRunner():Promise<main.RunnerInfo>;

export function GetSessionConversation(arg1:main.SessionPreviewRequest):Promise<main.SessionConversationResponse>;

export function GetSessionPreview(arg1:main.SessionPreviewRequest):Promise<main.SessionPreviewResponse>;

export function OpenPathInFinder(arg1:string):Promise<void>;

export function OpenProjectInFinder(arg1:string):Promise<void>;

export function RefreshProjectIndex(arg1:main.IndexRequest):Promise<main.ProjectIndexResponse>;

export function SaveConfig(arg1:main.AppConfig):Promise<main.AppConfig>;
